INSERT INTO t_students (c_id, c_name, c_patronymic, c_surname, c_status_of_students, c_group_id)
VALUES
    (1, 'Vladimir', 'Yurievich', 'Petrov', 'ACTIVE', 1),
    (2, 'Natalia', 'Alekseevna', 'Grigorieva', 'ACTIVE', 1),
    (3, 'Boris', 'Ivanovich', 'Karpov', 'ACTIVE', 1),
    (4, 'Irina', 'Leonidovna', 'Smirnova', 'ACTIVE', 1),
    (5, 'Sergei', 'Andreevich', 'Nikiforov', 'ACTIVE', 1),
    (6, 'Lyudmila', 'Pavlovna', 'Abramova', 'ACTIVE', 1),
    (7, 'Yaroslav', 'Vladimirovich', 'Bogdanov', 'ACTIVE', 1),
    (8, 'Diana', 'Igorevna', 'Zaitseva', 'ACTIVE', 2),
    (9, 'Gennady', 'Petrovich', 'Savin', 'ACTIVE', 2),
    (10, 'Lilia', 'Romanovna', 'Demina', 'ACTIVE', 2),
    (11, 'Timur', 'Sergeevich', 'Shestakov', 'ACTIVE', 2),
    (12, 'Veronika', 'Mikhailovna', 'Aksyonova', 'ACTIVE', 2),
    (13, 'Ruslan', 'Alexandrovich', 'Fomin', 'ACTIVE', 2),
    (14, 'Darya', 'Vadimovna', 'Yakovleva', 'ACTIVE', 2),
    (15, 'Ilya', 'Yurievich', 'Titov', 'ACTIVE', 3),
    (16, 'Vera', 'Artemovna', 'Nikonova', 'ACTIVE', 3),
    (17, 'Oleg', 'Evgenievich', 'Pankratov', 'ACTIVE', 3),
    (18, 'Kseniya', 'Viktorovna', 'Fedoseeva', 'ACTIVE', 3),
    (19, 'Stanislav', 'Denisovich', 'Loginov', 'ACTIVE', 3),
    (20, 'Taisiya', 'Semenovna', 'Ryabova', 'ACTIVE', 3);
